const ActionType = {};

ActionType.ADD_GAME_RECORD = "addGameRecord";
ActionType.ADD_MISC_CARD = "addMiscCard";
ActionType.ADD_ORDER_CARD = "addOrderCard";
ActionType.ADD_POOL_CARD = "addPoolCard";
ActionType.ADD_SITE_CARD = "addSiteCard";
ActionType.ADD_STRUCTURE = "addStructure";
ActionType.ADD_TO_PLAYER_ARRAY = "addToPlayerArray";
ActionType.SET_CARD_POOL = "setCardPool";
ActionType.SET_CURRENT_PHASE = "setCurrentPhase";
ActionType.SET_CURRENT_PLAYER = "setCurrentPlayer";
ActionType.SET_CURRENT_ROUND = "setCurrentRound";
ActionType.SET_CURRENT_STEP = "setCurrentStep";
ActionType.SET_DELAY = "setDelay";
ActionType.SET_JACK_DECK = "setJackDeck";
ActionType.SET_LEAD_ROLE = "setLeadRole";
ActionType.SET_MCTS_ROOT = "setMctsRoot";
ActionType.SET_ORDER_DECK = "setOrderDeck";
ActionType.SET_PLAYERS = "setPlayers";
ActionType.SET_PLAYER_STRATEGY = "setPlayerStrategy";
ActionType.SET_SITE_TO_DECK = "setSiteToDeck";
ActionType.SET_SITE_TO_OUT_OF_TOWN_DECK = "setSiteToOutOfTownDeck";
ActionType.SET_USER_MESSAGE = "setUserMessage";
ActionType.SET_VERBOSE = "setVerbose";
ActionType.SET_VERSION = "setVersion";
ActionType.SET_WINNER = "setWinner";
ActionType.TRANSFER_CAMP_TO_POOL = "transferCampToPool";
ActionType.TRANSFER_HAND_TO_CAMP = "transferHandToCamp";
ActionType.TRANSFER_HAND_TO_CLIENTELE = "transferHandToClientele";
ActionType.TRANSFER_HAND_TO_INFLUENCE = "transferHandToInfluence";
ActionType.TRANSFER_HAND_TO_STOCKPILE = "transferHandToStockpile";
ActionType.TRANSFER_HAND_TO_VAULT = "transferHandToVault";
ActionType.TRANSFER_JACK_TO_HAND = "transferJackToHand";
ActionType.TRANSFER_ORDER_TO_HAND = "transferOrderToHand";
ActionType.TRANSFER_ORDER_TO_POOL = "transferOrderToPool";
ActionType.TRANSFER_POOL_TO_CLIENTELE = "transferPoolToClientele";
ActionType.TRANSFER_POOL_TO_STOCKPILE = "transferPoolToStockpile";
ActionType.TRANSFER_STOCKPILE_TO_VAULT = "transferStockpileToVault";

Object.freeze(ActionType);

export default ActionType;
